### ISSUE TITLE
Roadmap for Virgo 2.0

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#10]
## Store
* [x] Support BlockModel and YBlock entities
* [x] Support WebRTC-based debug provider
* [x] Support slot-based events
* [x] Support block-wise undo/redo
* [x] Support cursor and awareness adapter
* [x] Support API for updating nested data structure
* Support IndexedDB provider
* [ ] Support importing workspace (as YDoc binary)
* [ ] Support exporting workspace (as YDoc binary)
* Support `defineModel` schema API

### Page
* [x] Support model class and basic rendering
* [x] Support adding block model to store on init
* [x] Support page title

### Text
* [x] Support rich text component
* [x] Support bold, italic, underline, strikethrough format
* [x] Support cursor on pressing arrow key up/down
* [x] Support switching between types
* [x] Support link
* [x] Support adding block on enter (cursor at line end)
* [x] Support splitting text block on enter (cursor at the middle of a line)
* [x] Support recognizing common markdown syntax 
  * `# ` headers
  * `* ` numbered list
  * `1. ` bulleded list
  * `[] ` to-do list
  * `**text**`  bold
  * `~text~` underline
  * `~~text~~` strikethrough
  * `***text***` bold and italic
* [ ] Support hotkeys
  * [x] `enter` (hard enter)
  * [x] `shift` + `enter` (soft enter)
  * [x] `cmd/ctrl` + `A` (select all)
  * [x] `cmd/ctrl` + `B` (bold)
  * [x] `cmd/ctrl` + `I` (italics)
  * [x] `cmd/ctrl` + `U` (underline)
  * [ ] `cmd/ctrl` + `shift` + `S` (strikethrough)
  * [ ] `cmd/ctrl` + `K` (link)
  * [x] `cmd/ctrl` + `E` (inline code)
  * [x] `tab` (indent)
  * [x] `shift` + `tab` (un-indent)
  * `cmd/ctrl` + `option/shift` + `0~9` (headers and paragraph)
  * `cmd/ctrl` + `+` (whiteboard)
  * `cmd/ctrl` + `-` (whiteboard)
  * [x] `shift` + `←/→`
  * [ ] `shift` + `↑/↓`

### List
* [x] Support basic rendering
* [x] Support indent and unindent
* [x] Support adding or splitting siblings on enter
* [ ] Support range delte
* [x] Support switching between numbered, bulleted and to-do style

### Image
* Support basic rendering
* Support drag and drop

## Editor
* [x] Support exporting to markdown
* [x] Support importing (pasting) from markdown
* [x] Support rich-text content copying and pasting
* [ ] Support React container

### Paper mode container
* [x] Support rendering paper mode selection box
* [x] Support hit test on basic text blocks
* [x] Support hit test on nested blocks
* [x] Support UI styling
* [ ] Support dark mode

### Endless mode container
* [x] Support panning and zooming container
* [ ] Support rendering endless mode selection box
* [ ] Support drawing basic shape

## Playground and test suite
* [x] Support E2E test suite and CI
* [x] Support multiplayer state asserting
* [x] Support text selection and store assertion
* [x] Support keyboard assertion
* [x] Support selection box assertion
* [x] Support building and package publishing automation
