### ISSUE TITLE
Replace Quill with Virgo

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#1219]
Initially we chose Quill for block-level rich text editing, but with the architecture of BlockSuite, only a subset of its features are actually used. So the plan is to replace Quill with Virgo, our ongoing rich text editing component.

Roadmap

- [x] Switch to Virgo in database block
- [x] Remove [quill-cursors](https://github.com/reedsy/quill-cursors), related to #1261 
- [x] Switch to Virgo in page title
- [ ] #1456
- [ ] Switch to Virgo in list and paragraph block
- [x] Switch to Virgo in code block

Notable progress (maintained by @Flrande)

- https://github.com/toeverything/blocksuite/pull/1433
- https://github.com/toeverything/blocksuite/pull/1377
- https://github.com/toeverything/blocksuite/pull/1168
- https://github.com/toeverything/blocksuite/pull/1146
- https://github.com/toeverything/blocksuite/pull/992
- https://github.com/toeverything/blocksuite/pull/912

Related

- #1413
- #1420

**Comment by Flrande** [comment]
`caretRangeFromPoint` doesn't work in shadow dom so we can not handle selection in multi-blocks level if we want to use shadow dom in our [rich-text](https://github.com/toeverything/blocksuite/blob/2f6e3fe7da18138fb88d187262467ac124e0861b/packages/blocks/src/__internal__/rich-text/rich-text.ts) component. But we can still use shadow dom if we just need one Virgo editor. It works well in [playground](https://blocksuite-toeverything.vercel.app/examples/virgo/).

https://bugs.chromium.org/p/chromium/issues/detail?id=388976

**Comment by doodlewind** [comment]
Closed as #1433 landed, cheers!
