### ISSUE TITLE
Reach whiteboard feature parity aligned with pre-alpha

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#1289]
We have refactored to a canvas-based renderer with basic whiteboard features in 0.4.0 (see #1268). In our next major release, our goal is to reach the feature parity with the [pre-alpha](https://livedemo.affine.pro/) version.

## Status

- Selection box (bounding box of the selected blocks and elements)
    - [x] Click on frame to position selection box
    - [x] Click on blank area to unselect
    - [x] Drag on box to move single block / element
    - [x] Drag on selection box handle to resize frame width
    - [x] Hover cursor style on selection box handle
    - [x] Size limit on drag and stretch (TODO #1288)
    - [ ] #1302
    - [ ] Drag on box to move multiple blocks / elements #1533
    - [ ] Support multiple selected frames / elements
    - [ ] Attach menu for modifying selected elements
- Selection frame (the rect based on start and end mouse position)
    - [x] Drag to select single frame
    - [ ] Drag to select multiple frames
    - [ ] Keyboard shortcuts support (command - A)
- Grouping
    - [ ] Basic data structure support
    - [ ] Create group from multiple selected blocks / elements
    - [ ] Drag group to move
    - [ ] Remove group
    - Batch resize (TBD)
- Shape tool
    - [x] Ellipse, rounded rect, triangle and diamond shapes https://github.com/toeverything/blocksuite/pull/1339
    - [x] Drag to add & resize
    - [ ] Update style in selected state
    - [ ] Customized hit test area
    - [ ] Keyboard shortcuts support (`R` / `T`...)
    - Double click to add associated text (TBD)
- Brush tool
    - [x] Support brush element in phasor #496
    - [x] Drag to draw
    - [ ] Customized hit test area
    - [ ] Style support (handwriting / solid / dash...)
    - [ ] Update styles in selected state
    - [ ] Keyboard shortcuts support
- Text tool
    - [ ] Click to add paragraph wrapped inside frame
    - [ ] Delete empty newly-added frame on clicking outside
    - [x] Double-click to enter edit state
- Layer sequence adjustment
    - Basic data structure support for frame blocks (TBD)
- Container capabilities
    - [x] Top-level pan & zoom
    - [x] Initial placement of frames
    - Snap (alignment) on dragging, or grid-based snapping (TBD)
    - Background grid lines (TBD)

## Notable Progress
- #1337
- #1339
- #1348
- #1412
- #1415
- #1417
- #1418
- #1423
- #1458

## Related

- #1294 
- #1293
- #1287

**Comment by tzhangchi** [comment]
Look forward to big changes of Whiteboard @alt1o

**Comment by doodlewind** [comment]
Minor issues & features prioritized this week:

* Support view control (zoom / pan) component
* Support zoom optimization
* Support adding multiple-frames
* Fix the active state issue
* Fix shape hit test issue
* Support deleting element
* Fix shape selection box after resize & undo

/cc @alt1o

**Comment by doodlewind** [comment]
Closing and tracked following progress in #1699 #1700 #1701.
