### ISSUE TITLE
Roadmap 202212

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#149]
We are mainly working on features for AFFiNE Alpha and data persistence.

* [x] #159
* [x] #160
* [x] #158
* [x] Support embed image block
* [x] Support inline popover menu (quick bar)
* [x] Support code block
* [x] Support workspace version

**Comment by doodlewind** [comment]
All done in `0.3.0-alpha.11`, thanks for the help from @darkskygit @DiamondThree @lawvs @QiShaoXuan @thorseraq  @JimmFly @colelawrence!

cc @tzhangchi @HeJiachen-PM
