### ISSUE TITLE
UX improvements & Bugs of tableview

### ISSUE THREAD

**Issue by tzhangchi** [toeverything/blocksuite#2184]
```[tasklist]
### Tasks
- [ ] link is not support to paste in text cell @zqran 
- [x] the length of enum value is too short @zqran 
- [x] Lost table data when I upgrade AFFiNE Client Version @zqran 
```

before
![c40a0cb4-3066-42ec-87c6-7b01f6284d4b](https://user-images.githubusercontent.com/5910926/233316742-2823b394-e7c1-42ad-aec1-cbe0383c86f5.jpeg)

after
<img width="991" alt="image" src="https://user-images.githubusercontent.com/5910926/233316579-b78d88b5-06b6-4aa0-9a26-8088a6e7ca04.png">

**Comment by tzhangchi** [comment]
@zqran  lost tableview data is a fatal bug

**Comment by Saul-Mirone** [comment]
The missing tableview data is caused by the breaking change of database model recently from https://github.com/toeverything/blocksuite/pull/2053. After internal syncing, we think it's acceptable since database hasn't been released.

**Comment by zqran** [comment]
> link is not support to paste in text cell

This problem is due to copy/paste being blocked. Now, only the selection area of the `rich-text` component can be obtained, but the text cell in the database is not based on the `rich-text` component. 

Should it support database when getting block selection? @lawvs

**Comment by zqran** [comment]
> link is not support to paste in text cell

The remaining issue is related to the `clipboard` and has been tracked in a separate issue(#2309). 

So, this issue can now be closed.
