### ISSUE TITLE
Improve edgeless mode usability

### ISSUE THREAD

**Issue by alt1o** [toeverything/blocksuite#2196]
```[tasklist]
# Features
- [ ] Support to create frames for presentation
- [ ] Support canvas rendering text. Scenario: add text to the shape / connector of the flowchart
- [ ] Support `lineStyle` for shape / connector #2166 
- [ ] Support copy / duplicate in the component toolbar
- [ ] Support `Copy as PNG` in the component toolbar
- [ ] Support the image tool in the edgeless toolbar
- [ ] Support grouping
- [ ] Support alignment
- [ ] Support snap
```

```[tasklist]
# Improvement
- [ ] `hittest` distinguishes between line and fill #2034
- [ ] Remove hover effect on elements #2033
- [ ] Handle single click and long press operations in active state of Connector #1974
- [ ] Show the nearest element's attach points when drawing a connector
- [ ] Click to add a fixed-size shape like FigJam
- [ ] Zoom size limitation
- [ ] Animation when zooming
```

```[tasklist]
# Shortcuts
- [ ] Select all: Ctrl / Command + a
- [ ] Duplicate: Ctrl / Option + Drag element #1811
- [ ] Multiple selections: Shift + Click element
- [ ] Resize element in origin scale: Shift + Drag resize handler #1873
```

```[tasklist]
# Compatible
- [ ] IPad / mobile events compatible, using `PointerEvent` to replace `MouseEvent` #2124
```

**Comment by doodlewind** [comment]
Closing for making place for new iteration scope
