### ISSUE TITLE
Clipboard enhancement [tasklist]

### ISSUE THREAD

**Issue by Brooooooklyn** [toeverything/blocksuite#2263]
```[tasklist]
### Tasks
- [ ] https://github.com/toeverything/blocksuite/issues/2173
- [ ] https://github.com/toeverything/blocksuite/issues/2183
- [ ] https://github.com/toeverything/blocksuite/issues/2228
- [ ] https://github.com/toeverything/blocksuite/issues/2236
- [ ] https://github.com/toeverything/AFFiNE/issues/2072
- [ ] https://github.com/toeverything/blocksuite/issues/1447
- [ ] https://github.com/toeverything/blocksuite/issues/2281
- [ ] https://github.com/toeverything/blocksuite/issues/2309
- [ ] https://github.com/toeverything/blocksuite/issues/2334
- [ ] https://github.com/toeverything/blocksuite/issues/2438
- [ ] https://github.com/toeverything/blocksuite/issues/2461
- [ ] https://github.com/toeverything/blocksuite/issues/3206
- [ ] https://github.com/toeverything/blocksuite/issues/2787
- [ ] https://github.com/toeverything/blocksuite/issues/3471
```

**Comment by doodlewind** [comment]
Closing since these are almost all finished.
