### ISSUE TITLE
Database improvements

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#2311]
```[tasklist]
### Tasks
- [ ] Determine the more appropriate view: overlay part of the content outside the page or add a modal dialog
- [x] Support Progress fields and checkbox fields
- [ ] https://github.com/toeverything/blocksuite/issues/2401
- [ ] Support sorting, filtering, and grouping (in increasing order of difficulty, possibly corresponding to priority)
```

**Comment by SolarDesalination** [comment]
Date field too please.

**Comment by doodlewind** [comment]
Closing this one since we've entered the housekeeping stage and we have shipped the main improvements in row-level selection in 0.6. We will open new issues for tracking more progress in database block. Thanks @zqran for your engagement!
