### ISSUE TITLE
Add `@blocksuite/lit` package

### ISSUE THREAD

**Issue by Saul-Mirone** [toeverything/blocksuite#2320]
- Start Date: 2023-04-27
- Status: Done

```[tasklist]
#### RFC PRs
- [x] https://github.com/toeverything/blocksuite/pull/2509
- [ ] https://github.com/toeverything/blocksuite/pull/2509
- [ ] https://github.com/toeverything/blocksuite/pull/2542
- [ ] https://github.com/toeverything/blocksuite/pull/2595
- [ ] https://github.com/toeverything/blocksuite/pull/2554
```

# Summary

We'll introduce a new `@blocksuite/lit` package to make it easier to share codes between blocks and the future hosts packages. This is also the precondition for blocksuite extension system.

# Lit Renderer

Since we want to separate the hosts and blocks, we need to extract the common pattern for rendering blocks in lit.

## Renderer Map

An editor may need to render same blocks to different views in different modes. For example, we may want to render the top-level page block as a *document view* or *edgeless view*, and we may also want to render all blocks as something like `read-only` blocks in an readonly editor.

Thus, we can have different maps to render different views for kinds of editors.

```ts
export const pagePreset = new Map<BlockSchemaType, StaticValue>([
  [PageBlockSchema, literal`affine-default-page`],
  [ListBlockSchema, literal`affine-list`],
  [FrameBlockSchema, literal`affine-frame`],
  [DatabaseBlockSchema, literal`affine-database`],
  [ParagraphBlockSchema, literal`affine-paragraph`],
]);

export const edgelessPreset = new Map<BlockSchemaType, StaticValue>([
  [PageBlockSchema, literal`affine-edgeless-page`],
  [SurfaceBlockSchema, literal`affine-surface`],
  [ListBlockSchema, literal`affine-list`],
  [FrameBlockSchema, literal`affine-frame`],
  [DatabaseBlockSchema, literal`affine-database`],
  [ParagraphBlockSchema, literal`affine-paragraph`],
]);
```

## Children Rendering

In previous versions of blocksuite. Every blocks will take care of the children rendering. This will increase the mental burden of developers. So we add a new property for each block view called `content`:

```ts
@customElement('affine-frame')
export class FrameBlockComponent extends ShadowlessElement {

  @property()
  model!: FrameBlockModel;

  @property()
  content!: TemplateResult;

  override render() {
    return html`
      <div class="affine-frame-block-container">
        <div class="affine-block-children-container">${this.content}</div>
      </div>
    `;
  }
}
```

## Removal of Legacy `host` Property

The `host` property in blocks is a out of date design and we'll remove it in this change.

## BlockElement and ShadowlessElement

We introduce two base class in @blocksuite/lit: `BlockElement` and `ShadowlessElement`.

### ShadowlessElement

ShadowlessElement creates lit element without shadow root. We all love shadow dom but it's not suitable to build rich text editor. So in blocksuite, all blocks are created without shadow root.

### BlockElement

Since all blocks follows same pattern when created, they'll have the same properties and methods when rendered, that's why we extract them into a base class.

Before:

```ts
@customElement('affine-paragraph')
export class ParagraphBlockComponent extends ShadowlessElement {
  @property()
  model!: ParagraphBlockModel;

  // some other props and methods...
}
```

After:

```ts
@customElement('affine-paragraph')
export class ParagraphBlockComponent extends BlockElement<ParagraphBlockModel> {
  // You've already get the properties
}
```

# Single Root Block

In previous versions of blocksuite, we have two root blocks: `page` and `surface`, which means we have a structure like:

```ts
[
  {
    role: 'root'
    flavour: 'affine:page',
    children: ['affine:frame'] 
  },
  {
    role: 'root'
    flavour: 'affine:surface',
  },
]
```

Have multiple roots will cause a lot of edge case issues and it's not clear in structure (imagine what will happen if dom can have multiple roots), so we made the `surface` as a child of `page`. Thus, `page` will be the only root in editor.

```ts
{
  role: 'root'
  flavour: 'affine:page',
  children: ['affine:surface', 'affine:frame'] 
}
```
