### ISSUE TITLE
Database support Kanban view

### ISSUE THREAD

**Issue by zqran** [toeverything/blocksuite#2401]
```[tasklist]
### Kanban Tasks
- [x] Split the directory structure of the database according to the view type.
- [x] Basic structure of the headless version of the kanban view.
- [ ] Support dragging to update the view.
```

**Comment by doodlewind** [comment]
I think this is expected to be handled by @zzj3720 in next scope.

**Comment by houjoe0829** [comment]
PRD：[Internal link](https://toeverything.feishu.cn/wiki/BBvQwisZ9i02ifkezi1cvdyenBc)

**Comment by hwangdev97** [comment]
Design file [Internal link](https://www.figma.com/file/rfH3P9Wbz4IEp2Ai18O8dV/%E2%96%B6%EF%B8%8F-Affine.2023.Jul?type=design&node-id=3907%3A8970&mode=design&t=kxcgQmoSCshExo9V-1)

**Comment by doodlewind** [comment]
Closed since we've landed #3629
