### ISSUE TITLE
Support bookmark

### ISSUE THREAD

**Issue by QiShaoXuan** [toeverything/blocksuite#2574]
### What

Another form of linking. In the current version, when we type or paste a link, the link is presented as inline text, and we need to support more presentation forms

### Why

- Better readability when referencing external web content, so you can get enough information without going outside the current site
- Embed Web is also a way AFFiNE and third-party apps can be interlinked, especially in Edgeless Mode

```[tasklist]
### Automatic detect link text
- [x] Automatic detect link text after input or paste, https://github.com/toeverything/blocksuite/pull/2624
- [x] After the link is identified, the selection menu should be displayed, https://github.com/toeverything/AFFiNE/pull/2458
```

```[tasklist]
### Bookmark block： <https://github.com/toeverything/blocksuite/pull/2693>
- [x] Add bookmark block
- [x] Interaction:
   - [x] Create by blockhub, slash menu
   - [x] Convert from link text by inline menu
- [x] Duplicate
- [x] Support Caption
- [x] Refresh
```

```[tasklist]
### Crawl information https://github.com/toeverything/AFFiNE/pull/2458
- [x] Follow the link for website information
```

**Comment by Svaney-ssman** [comment]
The design here: [internal link](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/AFFiNE-2023?type=design&node-id=2995-65127)

**Comment by xell** [comment]
Reopen as it's not finished.

**Comment by QiShaoXuan** [comment]
The basic function has done, smoe bugs and to be improved are recorded in https://github.com/toeverything/blocksuite/issues/2774
