### ISSUE TITLE
Advanced import format support in Notion and Markdown [tasklist]

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#2872]
Notion Support features:
- [x] Text 
- [x] Sub-page
- [x] Todo
- [x] Heading 1
- [x] Heading 2
- [x] Heading 3
- [x] Numbered list
- [x] Bulleted list
- [x] Quote
- [x] Divider
- [x] Callout
- [x] AI Blocks
- [x] Emoji
- [x] Toggle List       Mapping to a list
- [x] Table                Make sure the text content is not lost for now
- [x] Link to page        Tentative programme
- [x] Image                  Tentative programme
- [x] Web bookmark    Mapping to a link
- [x] Video.                    Mapping to a link
- [x] Audio.                  Mapping to a link.  Attachments not supported
- [x] Code.     The type and caption information is not brought over
- [x] File.        Mapping to a link.  Attachments not supported
- [x] Mention a person.     Tentative programme
- [x] Mention a page.      Tentative programme
- [x] Data or reminder.    Tentative programme
- [x] Inline equation.       Tentative programme
- [x] Embeds 21types.     Mapping to a link   Tentative programme
- [ ] Advanced blocks 13types
- [ ] Database 9types      
- [ ] SyncedDatabase  

Markdown Support features:
- [x] # Heading level 1
- [x] ## Heading level 2
- [x] ### Heading level 3
- [x] #### Heading level 4
- [x] ##### Heading level 5
- [x] ###### Heading level 6
- [x] Heading level 1
===============
- [x] Heading level 2
---------------
- [x]  **bold text**
- [x] __bold text__
- [x] *italic text*  
- [x]  _italic text_
- [x] ***bold italic text***  
- [x] ___bold italic text___ 
- [x] __*bold italic text*__  
- [x] **_bold italic text_**  
- [x] Code block     four spaces
- [x] > Quote
- [x]  Number List   
 1. First item
 2. Second item
 3. Third item
 4. Fourth item
- [x]  Number List   
1. First item
1. Second item
1. Third item
1. Fourth item
- [x]  Number List   
1. First item
8. Second item
3. Third item
5. Fourth item
- [x]  Number List   
1. First item
2. Second item
3. Third item
    1. Indented item
    2. Indented item
4. Fourth item
- [x]  Number List   
1. First item
2. Second item
3. Third item
    1. Indented item
    2. Indented item
4. Fourth item
- [x] Bulleted List
- First item
- Second item
- Third item
- Fourth item
- [x] Bulleted List
* First item
* Second item
* Third item
* Fourth item
- [x] Bulleted List
+ First item
+ Second item
+ Third item
+ Fourth item
- [x] Bulleted List
- First item
- Second item
- Third item
    - Indented item
    - Indented item
- Fourth item
- [x]  ` code text  `
- [x] ***   Sperate
- [x] ---   Sperate
- [x] ___  Sperate
- [x] Links  such as  [Afffine](https://affine.com)
- [x] URL or Email Such as <https://affine.com>  <aaa@affine.com>
- [x] Tables
| Syntax      | Description |
| ----------- | ----------- |
| Header      | Title       |
| Paragraph   | Text        |
- [x] Code      'type' information has not been supported
```json
{
  "firstName": "John",
  "lastName": "Smith",
  "age": 25
}
```
- [x] Todo List
   [ ] todo
   [x] todo
- [x] ~~strikethrough~~ 
- [ ] >> Nested Quote
- [ ] Images such as  ![aaa](/assets/images/aaa.png)      finished a few part work
- [ ] Reference-style   Sucn as  [aaa][bbb]
- [ ] Footnotes
- [ ] Definition Title
- [ ] Definition List
- [ ] Emoji  such as :emoji:
- [ ] ==highlight==
- [ ] Subscript such as H~2~O
- [ ] Superscript such as X^2^
- [ ] Prohibit URL parsing such as `http://www.example.com`

**Comment by doodlewind** [comment]
Closing since the remaining ones doesn't seem to have high priority for the moment.
