### ISSUE TITLE
Workspace Subdocument Support

### ISSUE THREAD

**Issue by Saul-Mirone** [toeverything/blocksuite#2964]
- Start Date: 2023-05-18
- Status: WIP

```[tasklist]
#### RFC PRs
- [x] https://github.com/toeverything/blocksuite/pull/2948
- [x] https://github.com/toeverything/blocksuite/pull/3147
- [x] https://github.com/toeverything/blocksuite/pull/3144
- [x] https://github.com/toeverything/blocksuite/pull/3156
- [x] https://github.com/toeverything/blocksuite/pull/3082
- [x] https://github.com/toeverything/blocksuite/pull/3157
- [x] https://github.com/toeverything/blocksuite/pull/3176
- [x] https://github.com/toeverything/blocksuite/pull/3182
```

# Summary

Add support for workspace subdocument. In the previous versions of @blocksuite/store, the workspace stores all pages as a Y.Map and load all of them when loading a workspace. For lazy load pages and cross page reconciling.

## Data Structure

```ts
// prev:
const store = Y.Doc({
  doc: Y.Map({
     [pageId]: Y.Map({
       [blockId]: Y.Map(props)
     })
   }),
   meta: Y.Map(metadata)
})

// current:
const store = Y.Doc({
  spaces: Y.Map({
    [pageId]: Y.Doc({
      blocks: Y.Map({
        [blockId]: Y.Map(props)
      })
    })
  }),
  meta: Y.Map(metadata)
})
```

**Comment by regischen** [comment]
the Y-model of phasor connector element will be refactored.
But I just started. maybe it cannot catch on this time.
