### ISSUE TITLE
Standard block spec

### ISSUE THREAD

**Issue by Saul-Mirone** [toeverything/blocksuite#3165]
- Start Date: 2023-06-19
- Status: WIP

> **Warning**
> This RFC is still in progress and the content maybe changed.

```[tasklist]
#### RFC PRs
- [ ] https://github.com/toeverything/blocksuite/pull/3164
- [ ] https://github.com/toeverything/blocksuite/pull/3175
- [ ] https://github.com/toeverything/blocksuite/pull/3635
- [ ] https://github.com/toeverything/blocksuite/pull/3637
- [ ] https://github.com/toeverything/blocksuite/pull/3644
- [ ] https://github.com/toeverything/blocksuite/pull/3645
- [ ] https://github.com/toeverything/blocksuite/pull/3646
- [ ] https://github.com/toeverything/blocksuite/pull/3647
- [ ] https://github.com/toeverything/blocksuite/pull/3653
- [ ] https://github.com/toeverything/blocksuite/pull/3662
- [ ] https://github.com/toeverything/blocksuite/pull/3674
- [ ] https://github.com/toeverything/blocksuite/pull/3685
- [ ] https://github.com/toeverything/blocksuite/pull/3692
- [ ] https://github.com/toeverything/blocksuite/pull/3699
- [ ] https://github.com/toeverything/blocksuite/pull/3703
- [ ] https://github.com/toeverything/blocksuite/pull/3715
- [ ] https://github.com/toeverything/blocksuite/pull/3718
- [ ] https://github.com/toeverything/blocksuite/pull/3722
- [ ] https://github.com/toeverything/blocksuite/pull/3734
- [ ] https://github.com/toeverything/blocksuite/pull/3801
- [ ] https://github.com/toeverything/blocksuite/pull/3815
- [ ] https://github.com/toeverything/blocksuite/pull/3826
- [ ] https://github.com/toeverything/blocksuite/pull/3865
- [ ] https://github.com/toeverything/blocksuite/pull/4471
- [ ] https://github.com/toeverything/blocksuite/pull/4504
```

```[tasklist]
### Sub topic issues
- [ ] https://github.com/toeverything/blocksuite/issues/4191
- [ ] https://github.com/toeverything/blocksuite/issues/2647
- [ ] https://github.com/toeverything/blocksuite/issues/2002
- [ ] https://github.com/toeverything/blocksuite/issues/2964
```

# Summary

A standard specification for define blocks in blocksuite.

# Structure

A block in blocksuite should contain:

- [x] Schema: data structure behind the block
  - [x] Flavour: A label for block defines what it is.
  - [x] Prop: The property of a block
  - [x] Model: A model for the block, which may contains some methods to operate the block data. 
- [ ] Service
  - [x] Event dispatcher: A singleton event handler to collect events should be handled by the block.
  - [x] Selection manager: Manage selection of the block.
  - [ ] Transformer: Defines how the block should be transformed into other structures, for example: HTML, JSON...
- [x] View
  - [x] Component: Define how the block should be rendered, in affine, blocks are rendered by lit.
  - [x] Widgets: A list of widgets that users can pass in to extend the view of the block. This can also be considered as some kind of view extension.

# Infra
- [x] Workspace Subdoc
- [x] Event Dispacher
- [x] Hotkey Binding
- [x] Service Manager
- [x] Selection Manager
- [x] View Store
- [ ] BS format

# WIP...

**Comment by doodlewind** [comment]
Closing since most of the entities are landed in v0.10, suggest adding new issues for further infra development.
