### ISSUE TITLE
Support new local-first playground entry

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#3372]
Currently the BlockSuite playground is used for local debug only, the providers config via URL params is very powerful, but hardly anyone uses it.

It would be great to add a new (more user-oriented) playground build entry that uses more opinionated provider strategy. Similar to the [tldraw.com](https://tldraw.com) and [excalidraw.com](https://excalidraw.com), it is expected to:

* Use IndexedDBProvider for local persistence default (when opening with no URL params).
* Switch to URL with room id when user clicks a *collaborate* button, connected to centralized room (and corresponding provider) at this moment.
* Use single-page workspace and is able to export JSON snapshot (then import it back).
* Hide most of the default debug menu and ship with simple but polished UI.

In this case, we can use this playground entry as a quick whiteboard *product* that can be used in a local-first way.

This won't affect E2E testing, having current playground migrated and maintained in a different URL should be trivial.
```[tasklist]
### Tasks
- [ ] https://github.com/toeverything/blocksuite/issues/3588
- [ ] storage support on server side
- [ ] polished UI/UX (awareness, collaboration related, etc.)
- [ ] binary resource uploading and sharing support (images, files, etc.)
```

**Comment by doodlewind** [comment]
This is transferred to @doouding after discussion, cheers.

**Comment by doouding** [comment]
@doodlewind I'm currently trying out the Cloudflare Worker. WebRTC might not be suitable when it comes to collaborating with more than two participants, because we need to broadcast update data to every user(if I understand correctly), which can be tedious to implement using WebRTC(because you have to establish P2P connection with every user in the same room). So I'll use WebSocket instead.

**Comment by doodlewind** [comment]
Closing since the initial effort is landed and we'll focus on bug fixes afterwards (like https://github.com/toeverything/blocksuite/issues/3764)
