### ISSUE TITLE
E2E regression fix

### ISSUE THREAD

**Issue by Saul-Mirone** [toeverything/blocksuite#3658]
With the https://github.com/toeverything/blocksuite/pull/3653, the old `selection-range` will be deprecated and all modules depends on that should migrate to the new `selection-manager` from block-std. We need to fix the e2e regressions marked with `test.fixme` to make sure the migration process is done.
```[tasklist]
### Tasks
- [ ] https://github.com/toeverything/blocksuite/pull/3674
- [ ] https://github.com/toeverything/blocksuite/pull/3703
- [ ] https://github.com/toeverything/blocksuite/pull/3715
- [ ] https://github.com/toeverything/blocksuite/pull/3718
- [ ] https://github.com/toeverything/blocksuite/pull/3802
- [ ] https://github.com/toeverything/blocksuite/pull/3816
- [ ] https://github.com/toeverything/blocksuite/pull/3833
- [ ] https://github.com/toeverything/blocksuite/pull/3859
- [ ] https://github.com/toeverything/blocksuite/pull/3866
- [ ] https://github.com/toeverything/blocksuite/pull/3869
- [ ] https://github.com/toeverything/blocksuite/pull/3895
- [ ] https://github.com/toeverything/blocksuite/pull/3900
- [ ] https://github.com/toeverything/blocksuite/pull/3901
- [ ] https://github.com/toeverything/blocksuite/pull/3903
- [ ] https://github.com/toeverything/blocksuite/pull/3904
- [ ] https://github.com/toeverything/blocksuite/pull/3925
- [ ] https://github.com/toeverything/blocksuite/pull/3930
- [ ] https://github.com/toeverything/blocksuite/pull/3942
- [ ] https://github.com/toeverything/blocksuite/pull/3948
- [ ] https://github.com/toeverything/blocksuite/pull/3950
- [ ] https://github.com/toeverything/blocksuite/pull/3952
- [ ] https://github.com/toeverything/blocksuite/pull/3953
- [ ] https://github.com/toeverything/blocksuite/pull/3955
- [ ] https://github.com/toeverything/blocksuite/pull/3966
- [ ] https://github.com/toeverything/blocksuite/pull/3974
- [ ] https://github.com/toeverything/blocksuite/pull/3975
- [ ] https://github.com/toeverything/blocksuite/pull/3980
- [ ] https://github.com/toeverything/blocksuite/pull/3984
- [ ] https://github.com/toeverything/blocksuite/pull/3985
```

**Comment by Saul-Mirone** [comment]
All e2e regressions fixed, cheers!
