### ISSUE TITLE
Update connector and shape toolbar UI

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/blocksuite#3714]
Connector: end point&start point were added
Shape: Shape with text was added

[figma](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=9978-245464&mode=design&t=r2IbtHpOD5Y42aYg-4)

![Image](https://github.com/toeverything/blocksuite/assets/110808979/f4e98310-aea1-4e58-85a9-9ccc88ebf16b)

![Image](https://github.com/toeverything/blocksuite/assets/110808979/6b52e3e5-69cb-451e-bb80-bbd27b83859d)

```[tasklist]
### Tasks
- [ ] https://github.com/toeverything/blocksuite/issues/4179
```

**Comment by doodlewind** [comment]
Temporality assign this to @regischen for future update, hopefully we can work on polishing edgeless UX details after we land frame.

**Comment by Svaney-ssman** [comment]
It remains following issues:

- [ ] 1. Fill style under general mode incorrect
- [ ] 2. icon/ button size and padding incorrect

<img width="153" alt="image" src="https://github.com/toeverything/blocksuite/assets/110808979/c404f77f-866f-492d-b59d-e12290a9ff1d"> 

<img width="144" alt="image" src="https://github.com/toeverything/blocksuite/assets/110808979/7dfe6bd2-015b-4d7f-b6a1-d96ca670e868"> 
<img width="97" alt="image" src="https://github.com/toeverything/blocksuite/assets/110808979/f0d2b729-bdf5-464f-b26f-df3899c4c4f4">

[please check the design](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=9978-245469&mode=dev)
<img width="1038" alt="image" src="https://github.com/toeverything/blocksuite/assets/110808979/c800eccb-8caf-4a57-ae44-4f488b8a1441">

- [ ] active status shows different  styles
<img width="760" alt="image" src="https://github.com/toeverything/blocksuite/assets/110808979/3d838127-3a73-489f-b97d-c7caa35f4f71">

The right design for the active icon is "hover filled color" background with 4px radius. check the [design](https://www.figma.com/file/UTTtfVCcStw1dKUg0gCSPo/%F0%9F%9B%9E-Design-System?type=design&node-id=956-8581&mode=design&t=sZVtS5a5MpmxotDU-4) as image shows 
<img width="1472" alt="image" src="https://github.com/toeverything/blocksuite/assets/110808979/4500e6fd-a18b-44c6-a57e-b35888b5dab7">

**Comment by regischen** [comment]
This may need @donteatfriedrice to take a look

**Comment by xell** [comment]
@regischen and/or @donteatfriedrice , please add @Svaney-ssman , who is responsible to the design, as one of the reviewers in the related PR(s) to make sure that the issue is actually resolved BEFORE closing it.

**Comment by regischen** [comment]
@xell ,I finished the component toolbar of connector in the sub-issue #4179 . And Before @donteatfriedrice developed the part related to shape. So I think we should responsible for the thing which we developed.

**Comment by donteatfriedrice** [comment]
> @xell ,I finished the component toolbar of connector in the sub-issue #4179 . And Before @donteatfriedrice developed the part related to shape. So I think we should responsible for the thing which we developed.

I will update the shape text toolbar ui, it seems that there is new design for the shape text part.

**Comment by doodlewind** [comment]
Closing after #4215 landed.
