### ISSUE TITLE
Improve of exporting html/markdown[TaskList]

### ISSUE THREAD

**Issue by zuoxiaodong0815** [toeverything/blocksuite#3846]
```[tasklist]
### Tasks
- [ ] https://github.com/toeverything/blocksuite/issues/3839
- [ ] https://github.com/toeverything/blocksuite/issues/3841
- [ ] empty block has not height in exported html
- [ ] support database block in exporting html
- [ ] support database block in exporting markdown
- [ ] https://github.com/toeverything/blocksuite/issues/3844
- [ ] https://github.com/toeverything/blocksuite/issues/3845
```
