### ISSUE TITLE
Support Kanban selection

### ISSUE THREAD

**Issue by zqran** [toeverything/blocksuite#4494]
```[tasklist]
### Tasks
- [x] Support shortcut keys to select different properties, and can also cross cards.
- [x] Supports shortcut keys to select different cards, and can also cross groups.
- [x] Support using shortcut keys (shift + left mouse button) to select multiple cards and drag.
- [x] Add tests for these features.
```
