### ISSUE TITLE
Database UI issues

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/blocksuite#4860]
- [ ] Resize and drag UI upgraded [in Design](https://www.figma.com/file/rfH3P9Wbz4IEp2Ai18O8dV/%E2%96%B6%EF%B8%8F-Affine.2023.Late?type=design&node-id=9097-60650&mode=design&t=za6ZfIjGpDDes4ix-4)
![Image](https://github.com/toeverything/blocksuite/assets/110808979/ab12192e-ae73-4f35-934b-3279c42c4625)

- [x] position of cell and menu need to be adjusted `transform = 'translate(-4px, -4px)';`
![image](https://github.com/toeverything/blocksuite/assets/110808979/27a8f845-0789-4c4b-95e4-0356674bc3e2)

```[tasklist]
### Tasks
- [ ] https://github.com/toeverything/blocksuite/issues/4861
- [ ] https://github.com/toeverything/blocksuite/issues/4863
```

**Comment by doodlewind** [comment]
Closing since database issues are being triaged alongside #5385
