### ISSUE TITLE
Enhance interoperability between doc and edgeless mode

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#5009]
This is the major editor functionality to be shipped in 0.10, which could make it smooth and immersive in content editing and presentation using AFFiNE. And the conceptual inconsistency between editor modes can also be resolved.

Key features included:

- Support top-level frame block, image block and group in edgeless mode, which can all be selectively visible in doc mode.
- Support auto connector indicator that connects through visible top-level edgeless contents.
- Support partially insert group and frame into doc mode.
- Support ToC based on top-level content rather than notes (TBD).

Issues breakdown:

```[tasklist]
### Major Tasks
- [ ] #4473
- [ ] #3594
- [ ] #4999
- [ ] https://github.com/toeverything/blocksuite/issues/5010
- [ ] https://github.com/toeverything/blocksuite/issues/5011
```

```[tasklist]
### Misc Detailed Improvements
- [ ] #4501
- [ ] #4978
- [ ] https://github.com/toeverything/blocksuite/issues/3367
- [ ] https://github.com/toeverything/blocksuite/issues/4616
- [ ] https://github.com/toeverything/blocksuite/issues/4936
- [ ] https://github.com/toeverything/blocksuite/issues/4937
- [ ] #4474
- [ ] https://github.com/toeverything/blocksuite/issues/4717
- [ ] https://github.com/toeverything/blocksuite/issues/4925
- [ ] #4940
- [ ] #4959
- [ ] #4935
- [ ] #4841
- [ ] https://github.com/toeverything/blocksuite/issues/4960
- [ ] #4938
- [ ] https://github.com/toeverything/blocksuite/pull/5043
- [ ] https://github.com/toeverything/blocksuite/pull/5062
- [ ] https://github.com/toeverything/blocksuite/pull/5037
- [ ] https://github.com/toeverything/blocksuite/pull/5074
- [ ] https://github.com/toeverything/blocksuite/pull/5064
- [ ] https://github.com/toeverything/blocksuite/pull/5141
```

```[tasklist]
### Perf
- [ ] #4167
- [ ] #4939
- [ ] https://github.com/toeverything/blocksuite/issues/5095
```

**Comment by doodlewind** [comment]
Closing since alls major tasks have been landed.
