### ISSUE TITLE
Drag Handle roadmap

### ISSUE THREAD

**Issue by Himself65** [toeverything/blocksuite#585]
# Features

- [x] basic implementation https://github.com/toeverything/blocksuite/pull/543
- [x] e2e test coverage https://github.com/toeverything/blocksuite/pull/560 https://github.com/toeverything/blocksuite/pull/575
- [x] singleton mode https://github.com/toeverything/blocksuite/pull/592 https://github.com/toeverything/blocksuite/pull/593
- [x] CSS move transition https://github.com/toeverything/blocksuite/pull/698
- [x] UI calibration with the AFFiNE team https://github.com/toeverything/blocksuite/pull/698

# Bug fixes
- https://github.com/toeverything/blocksuite/pull/557
- https://github.com/toeverything/blocksuite/pull/563
- https://github.com/toeverything/blocksuite/pull/579
- https://github.com/toeverything/blocksuite/pull/582 
- https://github.com/toeverything/blocksuite/pull/598
- https://github.com/toeverything/blocksuite/pull/604
- https://github.com/toeverything/blocksuite/issues/616
- https://github.com/toeverything/blocksuite/pull/607
- https://github.com/toeverything/blocksuite/pull/666
- https://github.com/toeverything/blocksuite/pull/854

## Need to be done in the future

- [ ] Drag/drop crossing 1-page height 
- [ ] Result correction on multiple users.

**Comment by himself65** [comment]
The drag handle is now stable to use.

Closing
