### ISSUE TITLE
DX improvement for model data tracing

### ISSUE THREAD

**Issue by himself65** [toeverything/blocksuite#711]
When we develop blocksuite, we treat the block; sometimes, we want to know which function causes a model update. What is the timeline of the block update? So this issue is talking about the DX improvement of the store part.

## Roadmap

- [x] enable debug log that only appears in playground dev #710 
- [ ] readable logs like git history for checking the timeline of a block update
- [ ] data viewer using a graphic library like d3.js
...

**Comment by doodlewind** [comment]
After #2002, the call stack of operations are pretty much improved. So this would be closed as not planned.
